# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [58]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [59]:
### [your code here]
print(np.__version__)

2.5.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [60]:
### [your code here]
a = np.random.rand(2, 3, 5)





### 4. Print a.


In [61]:
### [your code here]
print(a)

[[[0.71390725 0.7024593  0.92624815 0.70984347 0.58902967]
  [0.26130974 0.90426208 0.96319984 0.05632003 0.70938882]
  [0.45849612 0.53650975 0.30012053 0.15399764 0.66292649]]

 [[0.15323393 0.07834442 0.14755467 0.96251151 0.52976485]
  [0.75723128 0.51783947 0.6763254  0.57297266 0.73172663]
  [0.79717263 0.59915777 0.04582729 0.44667918 0.88474246]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [62]:
### [your code here]
b = np.random.randint(1, 2, size=(5, 2, 3))


### 6. Print b.


In [63]:
### [your code here]
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [64]:
### [your code here]
b.shape

(5, 2, 3)


### 8. Are you able to add a and b? Why or why not?


In [65]:
### [your code here]
## print(a+b)
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
#Not possible to add arrays of different shapes. The shapes of the two arrays must be compatible for broadcasting. In this case, the shapes (2, 3, 5) and (5, 2, 3) are not compatible for broadcasting because the dimensions do not match.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [66]:
### [your code here]
a.shape
c = b.transpose(1, 2, 0)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [67]:
### [your code here]
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [68]:
### [your code here]
print(d)


[[[1.71390725 1.7024593  1.92624815 1.70984347 1.58902967]
  [1.26130974 1.90426208 1.96319984 1.05632003 1.70938882]
  [1.45849612 1.53650975 1.30012053 1.15399764 1.66292649]]

 [[1.15323393 1.07834442 1.14755467 1.96251151 1.52976485]
  [1.75723128 1.51783947 1.6763254  1.57297266 1.73172663]
  [1.79717263 1.59915777 1.04582729 1.44667918 1.88474246]]]



### 12. Multiply a and c. Assign the result to e.


In [69]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [70]:
### [your code here]

print(e)
# in c all values are 1, so the result of the multiplication is the same as a.

[[[0.71390725 0.7024593  0.92624815 0.70984347 0.58902967]
  [0.26130974 0.90426208 0.96319984 0.05632003 0.70938882]
  [0.45849612 0.53650975 0.30012053 0.15399764 0.66292649]]

 [[0.15323393 0.07834442 0.14755467 0.96251151 0.52976485]
  [0.75723128 0.51783947 0.6763254  0.57297266 0.73172663]
  [0.79717263 0.59915777 0.04582729 0.44667918 0.88474246]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [71]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)



1.9631998395946715 1.0458272868112326 1.5516367664173094



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [72]:
### [your code here]
f = np.empty_like(d)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [73]:
### [your code here]
f = np.select(
    [
        d == d_min,
        (d > d_min) & (d < d_mean),
        d == d_mean,
        (d > d_mean) & (d < d_max),
        d == d_max
    ],
    [0, 25, 50, 75, 100]
)
print(f)

[[[ 75  75  75  75  75]
  [ 25  75 100  25  75]
  [ 25  25  25  25  75]]

 [[ 25  25  25  75  25]
  [ 75  25  75  75  75]
  [ 75  75   0  25  75]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [74]:
### [your code here]
print(d)
print(f)

[[[1.71390725 1.7024593  1.92624815 1.70984347 1.58902967]
  [1.26130974 1.90426208 1.96319984 1.05632003 1.70938882]
  [1.45849612 1.53650975 1.30012053 1.15399764 1.66292649]]

 [[1.15323393 1.07834442 1.14755467 1.96251151 1.52976485]
  [1.75723128 1.51783947 1.6763254  1.57297266 1.73172663]
  [1.79717263 1.59915777 1.04582729 1.44667918 1.88474246]]]
[[[ 75  75  75  75  75]
  [ 25  75 100  25  75]
  [ 25  25  25  25  75]]

 [[ 25  25  25  75  25]
  [ 75  25  75  75  75]
  [ 75  75   0  25  75]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [76]:
f = np.select(
    [
        d == d_min,
        (d > d_min) & (d < d_mean),
        d == d_mean,
        (d > d_mean) & (d < d_max),
        d == d_max
    ],
    ["A", "B", "C", "D", "E"],
    default=""
)

print(f)

[[['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'E' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']]

 [['B' 'B' 'B' 'D' 'B']
  ['D' 'B' 'D' 'D' 'D']
  ['D' 'D' 'A' 'B' 'D']]]
